clang-tidy: fix missing include for uint32_t
Fixed the following error by including the <cstdint> header file.

'''
watchdog/watchdog_logging.hpp:23:33: error: unknown type name 'uint32_t' [clang-diagnostic-error]
   23 | void eventWatchdogTimeout(const uint32_t timeout);
'''

Change-Id: I3cee346296fa0c9925e920f5abc04470b15ad278
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>